### ISSUE TITLE
Acceso a Figma

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#18]
Hola juli, tengo solo permiso para ver y no para editar/agregar nada en Figma.

<img width="921" alt="Captura de Pantalla 2021-08-17 a la(s) 03 16 45" src="https://user-images.githubusercontent.com/49484934/129673507-b66fd8b7-1353-4709-8a63-1579314b0614.png">

**Comment by sobrinojulian** [comment]
creo que ya esta, le di `can edit` para `indeciso vampiro` y `valentin guillan`. En caso de que no puedas, se puede reabrir el issue
