### ISSUE TITLE
Links en Editorial y compartidas

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#23]
Hola. Cuando escribo los enlaces con arroba me tira el url en vez de generar el enlace en la palabra.  Y en el cms me pide un campo de instagram que no veo donde lo agrega a la pagina como enlace.

Los nombres de quienes hacen cada fanzine y sus cuentas de instagram quedan muy grandes. 

ahh y pongo compartir desde el boton de facebook por ejemplo, me aparece el logo de indeciso vampiro, estaría bueno que se vea alguna imagen del fanzine que quiero compartir. 

<img width="1046" alt="Captura de Pantalla 2021-08-17 a la(s) 05 43 51" src="https://user-images.githubusercontent.com/49484934/129693974-9adf5822-bff9-4e0c-899f-9af8d9e1e08c.png">

![image](https://user-images.githubusercontent.com/49484934/130561077-8c5abaf0-3465-424b-8079-cfda8696e66a.png)

<img width="559" alt="Captura de Pantalla 2021-08-17 a la(s) 05 45 36" src="https://user-images.githubusercontent.com/49484934/129694249-cf081c90-1e85-40ea-9392-6fd0420d4783.png">

**Comment by sobrinojulian** [comment]
Mañana lo hago a este, ya vi como arreglar todos los puntos, pero paja hacerlo ahora

**Comment by sobrinojulian** [comment]
> ahh y pongo compartir desde el boton de facebook por ejemplo, me aparece el logo de indeciso vampiro, estaría bueno que se vea alguna imagen del fanzine que quiero compartir.
Falta esto nomas

**Comment by valentinguillan** [comment]
Faltó lo de la imagen de las portadas de los fanzines cuando se comparte en facebook y eso. Pero está re piolazooooo

![image](https://user-images.githubusercontent.com/49484934/131377893-eb2cb29c-679f-48cd-9403-98d50435d51e.png)
