### ISSUE TITLE
Agregar unas barra más (Flashcookie)

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#24]
Hoola. Te mando una captura medio cabeza de lo que habría que agregar al final. Iría después de editorial. Tendría el siguiente link en la cara del chabon galleta y donde dice flash cookie:

indeciso-vampiro.flashcookie.com

Despues te lo armo en figma no?

Saludos!
<img width="785" alt="Captura de Pantalla 2021-08-17 a la(s) 06 06 22" src="https://user-images.githubusercontent.com/49484934/129697301-d3f0ae34-2259-49e7-839c-07a69980aef3.png">

**Comment by sobrinojulian** [comment]
Ahi lo puse lo puse como una imagen para safar. Despues lo dejo para que se haga click donde decis y ademas que se vea bien en mobile

**Comment by valentinguillan** [comment]
Papu de que parte me hablas

**Comment by valentinguillan** [comment]
Así ya queda buenisimo igual jaja :)
