### ISSUE TITLE
Precio en editorial

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#25]
Buenas!, estaría bueno que en la casilla de "precio" se pueda incluir texto y no solo numeros. Porque hay algunos en los que quiero escribir "Agotado" 

<img width="831" alt="Captura de Pantalla 2021-08-24 a la(s) 01 25 00" src="https://user-images.githubusercontent.com/49484934/130555566-8c256dba-8398-4079-a18f-3d78e1462e5f.png">

**Comment by sobrinojulian** [comment]
Agregue esta opcion el cms
![Screenshot_2021-08-24_17-12-22](https://user-images.githubusercontent.com/34169391/130683426-14946fff-4880-4e7d-9aca-d6f2945d5eda.png)

y se refleja asi
![Screenshot_2021-08-24_17-15-28](https://user-images.githubusercontent.com/34169391/130683745-7a9650b4-5368-4f39-8aaa-4e6c3a4e0f23.png)

**Comment by valentinguillan** [comment]
Sape
