### ISSUE TITLE
Nueva seccion ENCUENTROS

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#26]
Bueenas. Habría que agregar con la misma lógica de "Invaiosn indecisa" y "sesiones indecisas" esta sección. 
¿Cómo hacemos para pasarte todo de la forma más cómoda para vos? 

<img width="195" alt="Captura de Pantalla 2021-08-24 a la(s) 03 58 33" src="https://user-images.githubusercontent.com/49484934/130571272-335f28a6-0cf9-4be9-a5da-c0d562d01c53.png">

**Comment by sobrinojulian** [comment]
Ahi en el figma puse esto:
![Screenshot_2021-08-24_18-21-12](https://user-images.githubusercontent.com/34169391/130691766-1fd1c75a-a924-499b-80ce-fbc007127534.png)

## Pasamelo de cualquiera de estas formas
- Si queres pasamelo en figma asi como agregue ese de la imagen de arriba

- Sino tirame un zip como este que adjunto, que tendria los logos, la imagen y el contenido. o el contenido ponelo aca como un comentario.
[zip.zip](https://github.com/somosliana/indecisovampiro.com.ar/files/7042191/zip.zip)

- Si lo tenes hecho en algo de adobe y tiene una opcion de compartirlo tipo figma, pasame ese link y saco las imagenes de ahi.

## Despues agrego la opcion al cms
Y me agrego como tarea el agregar esto y lo de audiovisual. Que diga: "Logo", "Titulo"  "Descripcion", "Imagen", "Fondo" "link"

**Comment by valentinguillan** [comment]
che juli y como entro a ese figma ?

**Comment by valentinguillan** [comment]
si lo puedo hacer, te lo paso aca tengo los archivos papu

**Comment by valentinguillan** [comment]
Fijate que ya puse las secciones de encuentro y la barra de instragram en el Figma. Avisame si te funciona así o te paso de otra forma. 

<img width="379" alt="Captura de Pantalla 2021-08-25 a la(s) 03 45 42" src="https://user-images.githubusercontent.com/49484934/130739958-8bd53109-d6f3-4bed-ab26-e916d7a50b4c.png">
