### ISSUE TITLE
Abrir playlist en una pestaña nueva

### ISSUE THREAD

**Issue by valentinguillan** [somosliana/indecisovampiro.com.ar#34]
Se puede hacer que cuando se presione en las tapas de las playlist se abran en una pestaña nueva? 

<img width="994" alt="Captura de Pantalla 2021-09-01 a la(s) 00 40 48" src="https://user-images.githubusercontent.com/49484934/131608063-c8a2d4ed-53f9-4ce8-bae6-fcf6aa13558c.png">

**Comment by sobrinojulian** [comment]
si wil, bien ahi no me di cuenta. ya casi termino lo de que se vea bien cuando se comparte en facebook y arreglo esto
